users:
  maximum_name: 100
  maximum_email: 255
  seed_record: 64
  per_page: 10
posts:
  maximum_title_length: 1000
  per_page: 10
  timestr: "%B %d, %Y"
  seed_record: 50
  user_taked: 8
  title_sentence: 1
  body_sentence: 8
  des_sentence: 1
tags:
  maximum_tag_content: 100
comments:
  maximum_comtents_length: 1000
pictures:
  resize_to_limit_width: 1000
  resize_to_limit_height: 800
ckeditor:
  thumb_width: 118
  thumb_height: 100
  content_width: 800
  content_height: 800
follow:
  min_following: 2
  max_following: 50
  min_followers: 3
  max_followers: 40
  per_page: 8
